service: aws-hackathon-2025-lambda-service
frameworkVersion: "3"

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  vpc:
    securityGroupIds:
      - sg-00a657f7937fec983
    subnetIds:
      - subnet-0794c881d326871ea
      - subnet-0a08f6e41e4896b2e

  environment:
    QUEUE_URL: https://sqs.us-east-1.amazonaws.com/975049899047/sqs-hackathon-2025
    SECRET_NAME: rds!cluster-709bbecc-8432-4da5-8727-aafbf13556e3
    DB_URL: database-2.cluster-ckdseak4qyg6.us-east-1.rds.amazonaws.com
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sqs:SendMessage
      Resource: arn:aws:sqs:us-east-1:975049899047:sqs-hackathon-2025
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
        - secretsmanager:DescribeSecret
      Resource: arn:aws:secretsmanager:us-east-1:975049899047:secret:rds!cluster-709bbecc-8432-4da5-8727-aafbf13556e3-c6E7hE

functions:
  videoReceiver:
    handler: handler.video_receiver
    memorySize: 128
    timeout: 29
    events:
      - httpApi:
          method: POST
          path: /video-url

package:
  patterns:
    - "!node_modules/**"
    - "!__pycache__/**"
    - "**/*.py"
    - "requirements.txt"

plugins:
  - serverless-python-requirements
  - serverless-offline

custom:
  pythonRequirements:
    fileName: requirements.txt
    usePoetry: false
    layer: false # (set true if you prefer a layer)
    dockerizePip: non-linux
    slim: false # remove tests/docs to shrink size
    invalidateCaches: true # bust cache if you’re fighting stale wheels
  serverless-offline:
    httpPort: 3000
