AWS_REGION = "us-east-1"
LANGUAGE_CODE="en"

S3_BUCKET_NAME = "clip-highlights-bucket"
S3_REGION = "us-east-1"
IMAGE_BUCKET_PREFIX = "images/frame/"
AUDIO_BUCKET_PREFIX = "audio/streams/"


DB_NAME="strangedb"
VIDEO_METADATA_TABLE_NAME = "video_metadata"
AUDIO_METADATA_TABLE_NAME = "audio_metadata"
SCORE_METADATA_TABLE = "score_metadata"
STREAM_METADATA_TABLE = "stream_metadata"

DB_HOST = "database-2.cluster-ckdseak4qyg6.us-east-1.rds.amazonaws.com"
DB_PORT = 3306
DB_SECRET_NAME = "rds!cluster-709bbecc-8432-4da5-8727-aafbf13556e3"

# AUDIO CONFIGURATION
TARGET_SAMPLE_RATE = 16000
AUDIO_CHUNK = 5

# VIDEO CONFIGURATION
VIDEO_FRAME_SAMPLE_RATE = 2

# SALIENCY CONFIGURATION
SALIENCY_THRESHOLD = 0.7


# SLICE
CANDIDATE_SLICE = 5
STEP_BACK = 2

# LOCAL STORAGE
BASE_DIR = "./data"

MAX_STREAM_DURATION = 600